### ISSUE TITLE
front/only-mobile-pages

### ISSUE THREAD

**Issue by Branyoe** [MyUDC/MiUDC#11]
## Descripción
En el layout principal de la aplicación, implementa estilos con Tailwind para que, en caso de que la aplicación se muestre en una pantalla grande (mayor a "sm"), aparezca una alerta indicando que, por el momento, la aplicación solo funciona en pantallas "sm".
Ruta del layout principal:
`/src/app/layout.tsx`

## Subtareas
...

## Notas
- para iniciar con la issue:
  - Llena el campo "Start date" de la issue 
   `git fetch origin`
   `git checkout front/#6/maquetado_register_page`

## Documentación
- https://tailwindcss.com/docs/theme

## Diseño
El diseño está pendiente, contactar a @EduardoChacom para definirlo o en su defecto implementar un diseño generico temporal.

**Comment by LUISPINTO90** [comment]
Viejo... yo diría que en vez de limitarla hay que hacerla responsive
